### ISSUE TITLE
Missing functions.php

### ISSUE THREAD

**Issue by bystrzan** [Happster/Wordpress-material-design-theme#1]
There's no functions.php so no child-theme files loaded :)

**Comment by Happster** [comment]
Hi  inkm, sorry didn't had much time to finish this theme.. anyways, now all files are here so you can give it a go :)

**Comment by bystrzan** [comment]
Have the same :) Never have enought time to put my work into be or github :)
Btw - I still looking for another projects using/ inspired GMD but I think I have to put my version soon. 
Best from PL

**Comment by Happster** [comment]
Let me know when you done and we will [add to our showcase](http://materialdesignblog.com/submit-your-design/)
